// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dydosyheairmgbxdlnpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZG9zeWhlYWlybWdieGRsbnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTM4NDgsImV4cCI6MjA3Mzc2OTg0OH0.X7MIKy41XnYlQ90o1_1LuLTO54MR4DQJ1WD4-HbDm68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});